<a href="https://colab.research.google.com/github/reddy8888/ML_Assignment1/blob/main/ML_ICP3_700756460.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

random_vector = np.random.randint(1, 21, size=15)

reshaped_array = random_vector.reshape(3, 5)

print("Shape of the array after reshaping to 3 by 5:", reshaped_array.shape)

reshaped_array[np.arange(len(reshaped_array)), np.argmax(reshaped_array, axis=1)] = 0

print("Array after replacing max in each row by 0:\n", reshaped_array)

array_2d = np.random.randint(0, 256, size=(4, 3), dtype=np.int32)

print("\nShape of the 2D array:", array_2d.shape)
print("Type of the array:", type(array_2d))
print("Data type of the array:", array_2d.dtype)


Shape of the array after reshaping to 3 by 5: (3, 5)
Array after replacing max in each row by 0:
 [[15  0 18  1  5]
 [ 2  8  0  1 11]
 [14  0  9 15 13]]

Shape of the 2D array: (4, 3)
Type of the array: <class 'numpy.ndarray'>
Data type of the array: int32


In [2]:
import numpy as np

square_array = np.array([[3, -2], [1, 0]])

eigenvalues, right_eigenvectors = np.linalg.eig(square_array)

print("Eigenvalues:")
for eigenvalue in eigenvalues:
    print(eigenvalue)

print("\nRight Eigenvectors:")
for i in range(len(right_eigenvectors)):
    print("Eigenvalue:", eigenvalues[i])
    print("Right Eigenvector:", right_eigenvectors[:, i])

Eigenvalues:
2.0
1.0

Right Eigenvectors:
Eigenvalue: 2.0
Right Eigenvector: [0.89442719 0.4472136 ]
Eigenvalue: 1.0
Right Eigenvector: [0.70710678 0.70710678]


In [3]:
import numpy as np

array = np.array([[0, 1, 2], [3, 4, 5]])

diagonal_sum = np.trace(array)

print("Sum of diagonal elements:", diagonal_sum)

Sum of diagonal elements: 4


In [4]:
import numpy as np

original_array_3x2 = np.array([[1, 2], [3, 4], [5, 6]])
original_array_2x3 = np.array([[1, 2, 3], [4, 5, 6]])

reshaped_array_2x3 = np.reshape(original_array_3x2, (2, 3))

reshaped_array_3x2 = np.reshape(original_array_2x3, (3, 2))

print("Reshaped array 2x3:")
print(reshaped_array_2x3)

print("\nReshaped array 3x2:")
print(reshaped_array_3x2)


Reshaped array 2x3:
[[1 2 3]
 [4 5 6]]

Reshaped array 3x2:
[[1 2]
 [3 4]
 [5 6]]
